---
output:
  pdf_document:
    latex_engine: xelatex
    
fontsize: 12pt
geometry: margin=0.50in
subparagraph: yes
params: 
    title:
      value: x
    date:
      value: x
    baseDir:
      value: x

title: "`r params$title`"
date:  "`r params$date`"
baseDir: "`r params$baseDir`"
header-includes:
   - \usepackage{pdflscape}
   - \newcommand{\blandscape}{\begin{landscape}}
   - \newcommand{\elandscape}{\end{landscape}}
   - \usepackage{pdfpages}
   - \usepackage{booktabs}
   - \usepackage{longtable}
   - \usepackage{makecell}
   - \usepackage{float}
---

\vspace{-1cm}


```{r setup, cache = FALSE, echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)
library(knitr)
library(kableExtra)
library(stringr)
library(dplyr)
library(tidyr)
library(lubridate)

baseDir <- params$baseDir
##test inputs start
# baseDir <- '/home/agmcfarland/quick_tests/output'
##test inputs end

```

# Run Outcomes Overview
```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

## load filepaths
runStats_filepath <- paste0(baseDir,'/runStats.csv')
softwareVersions_filepath <- paste0(baseDir,'/softwareVersions.txt')
# create the sample folder paths
sampleDir_folderpath <- c()
for (s in as.character(read.csv(runStats_filepath)$sample) ){
  sampleDir_folderpath <- c(sampleDir_folderpath, paste0(baseDir,'/sampleOutputs/',s))
}

## Run outputs location
cat(paste0('\n**Run output directory: **',baseDir  ,'\n'))


## Number of samples processed, run time, error counts (summarized)
# edit df_runStats for plotting with kable
df_runStats <- read.csv(runStats_filepath)%>%
  mutate(error_status = as.character(error_status),
               error_status = replace_na(error_status,'No error'))%>%
  mutate(time_ran_formatted = hms(time_ran))%>%
  arrange(desc(time_ran_formatted))

cat(paste0('\n**Samples processed: **',nrow(df_runStats)  ,'\n'))

cat(paste0('\n**Run time: **', round(df_runStats%>%select(time_ran_formatted)%>%slice(1)%>%pull(),0)  ,'\n'))

cat('\n**Errors: **\n')

kable(df_runStats%>%
        group_by(error_status)%>%
        summarize(count=n())%>%
        arrange(desc(count))%>%
        rename(`Error Status`=1, Count=2),
      'latex', booktabs = T, linesep = '', align = 'c')%>%
  kable_styling(font_size = 10,latex_options="hold_position",position='center')

## reference strain selected
referenceStrains <- list()
for ( sampleDir in sampleDir_folderpath ){
  samplename <- basename(sampleDir)
  refStrain <- tryCatch({
    str_remove(as.character(read.csv(paste0(sampleDir,'/reference_ha_coverage_',samplename,'.csv'))[1,1]), '_coverage_stats.csv')
    }, error = function(e){
      'no reference'
    })
  referenceStrains[[samplename]] <- refStrain
}

df_referenceStrains <- stack(referenceStrains)%>%
  rename('reference_strain'=1, 'sample'=2)

cat('\n**Reference strain counts:**\n')
kable(df_referenceStrains%>%
        group_by(reference_strain)%>%
        summarize(count=n())%>%
        arrange(desc(count))%>%
        rename(`Reference Strain`=1, Count=2),
      'latex', booktabs = T, linesep = '', align = 'c')%>%
  kable_styling(font_size = 10,latex_options="hold_position",position='center')

```

\newpage
# Read Coverage

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=8, fig.height=3.25, results='asis'}

## coverage stats
df_covStats <- data.frame()
for ( sampleDir in sampleDir_folderpath ){
  samplename <- basename(sampleDir)
  sample_CovStat <- tryCatch({
    read.csv(paste0(sampleDir,'/',samplename,'_covstats.txt'),sep='\t')
    }, error = function(e){
      data.frame()
    })
  if( nrow(sample_CovStat)>0 ){
    sample_CovStat$sample <- samplename
  }
  df_covStats <- rbind(df_covStats, sample_CovStat)
}

ggplot(df_covStats%>%
         mutate(segment_id=stringr::str_sub(X.ID,start=-1))%>%
         select(segment_id,sample,Covered_percent,Avg_fold,Median_fold)%>%
         pivot_longer(cols=c(Covered_percent,Avg_fold,Median_fold), names_to = "map_stats", values_to = "value")%>%
         mutate(map_stats=factor(map_stats,levels=c('Covered_percent','Avg_fold','Median_fold')),
                map_stats=recode(map_stats,
                                 Covered_percent='Coverage (%)',
                                 Avg_fold='Average fold\ncoverage',
                                 Median_fold='Median fold\ncoverage')),
       aes(y=value,x=segment_id))+
  facet_wrap(~map_stats, scales='free',nrow=3, strip.position='right')+
  geom_boxplot(outlier.shape=NA,alpha=0,width=0.25)+
  geom_point(position=position_jitter(width=0.2,height=0),alpha=0.5)+
  theme_classic()+
  theme(panel.grid.major.y = element_line(size=0.5,linetype='dashed',color='lightgrey'),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.spacing = unit(0, 'lines'),
        strip.text = element_text(size=14, colour='gray50'),
        strip.text.y = element_text(angle=0),
        strip.background = element_blank(), # getting rid of the panel to declutter
        axis.line = element_line(colour = 'black'),
        axis.text.y = element_text(size=10),
        axis.text.x = element_text(size=7),
        axis.title.y = element_blank(),
        legend.position='none',
        legend.title = element_blank())+
  xlab('Segment')


```

# HA Strain Assignment Coverage

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=8, fig.height=3.25, results='asis'}

df_haCoverage <- data.frame()
for ( sampleDir in sampleDir_folderpath ){
  samplename <- basename(sampleDir)
  haCoverage <- tryCatch({
    read.csv(paste0(sampleDir,'/reference_ha_coverage_',samplename,'.csv'))
    }, error = function(e){
      data.frame()
    })
  df_haCoverage <- rbind(df_haCoverage,haCoverage)
}



ggplot(df_haCoverage%>%
         group_by(sample)%>%
         arrange(desc(ha_coverage))%>%
         slice(1)%>%
         ungroup()%>%
         mutate(reference=str_remove(reference,'_coverage_stats.csv'),
                ha_coverage=round(ha_coverage*100,2),
                ha_read_depth=round(ha_read_depth,2))%>%
         pivot_longer(cols=c(ha_coverage, ha_read_depth), names_to='cov_stats', values_to='value')%>%
         mutate(cov_stats=factor(cov_stats, levels=c('ha_coverage','ha_read_depth')),
                cov_stats=recode(cov_stats,
                                 ha_coverage='HA Coverage (%)',
                                 ha_read_depth='HA Average\nread depth'))
       ,
       aes(y=value,x=reference))+
  facet_wrap(~cov_stats, scales='free',nrow=2, strip.position='right')+
  geom_boxplot(outlier.shape=NA,alpha=0, width=0.25)+
  geom_point(position=position_jitter(width=0.2,height=0),alpha=0.5)+
  theme_classic()+
  theme(panel.grid.major.y = element_line(size=0.5,linetype='dashed',color='lightgrey'),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.spacing = unit(0, 'lines'),
        strip.text = element_text(size=14, colour='gray50'),
        strip.text.y = element_text(angle=0),
        strip.background = element_blank(), # getting rid of the panel to declutter
        axis.line = element_line(colour = 'black'),
        axis.text.y = element_text(size=10),
        axis.text.x = element_text(size=7),
        axis.title.y = element_blank(),
        legend.position='none',
        legend.title = element_blank())+
  xlab('Reference')

```

\newpage

# All Run Outcomes

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

kable(df_runStats%>%
        select(sample,error_status,time_ran_formatted)%>%
        arrange(desc(time_ran_formatted))%>%
        mutate(time_ran_formatted=round(time_ran_formatted,0))%>%
        rename(Sample=1,`Error status`=2, Runtime=3),
      'latex', booktabs = T, linesep = '', align = 'c', longtable=TRUE)%>%
  kable_styling(font_size = 10,latex_options=c('hold_position','repeat_header'),position='center')

```

\newpage

# All Reference Strains

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

kable(df_referenceStrains%>%
        arrange(reference_strain,sample)%>%
        rename(`Reference Strain`=1, Sample=2)%>%
        select(Sample,`Reference Strain`),
      'latex', booktabs = T, linesep = '', align = 'c', longtable=TRUE)%>%
  kable_styling(font_size = 10,latex_options=c('hold_position','repeat_header'),position='center')

```

\newpage

# Software

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

df_softwareVersions <- read.csv(softwareVersions_filepath,sep='\t',header=FALSE,comment.char = '#')%>%
  rename('Package'=1)

core_packageList <- c('samtools','bwa','bbmap','bamutil','biopython','nextclade','python=','r-base=')

found_core <- list()
for ( i in df_softwareVersions$Package ){
  for ( x in core_packageList ){
    if ( str_detect(i, x) ){
      found_core[[x]] <- i
    }
  }
}

found_core <- stack(found_core)%>%
  rename('Package'=1, 'indicator'=2)%>%
  mutate(core_package='core')%>%
  select(-indicator)

df_softwareVersions <- merge(df_softwareVersions,found_core,by='Package',all=TRUE)

kable(df_softwareVersions%>%
        arrange(core_package)%>%
        select(-core_package),
      'latex', booktabs = T, linesep = '', align = 'c', longtable=TRUE)%>%
  kable_styling(font_size = 10,latex_options=c('hold_position','repeat_header'),position='center')

```




